/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bspatch_test_BSPatchDemo */

#ifndef _Included_com_bspatch_test_BSPatchDemo
#define _Included_com_bspatch_test_BSPatchDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bspatch_test_BSPatchDemo
 * Method:    SayHello
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT int JNICALL Java_com_bspatch_test_BSPatchDemo_combine
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
